# docker-compose.yml for AzerothCore.
#
# Start the server with `docker compose up -d --build`
#
# Don't make changes this file! make a `docker-compose.override.yml` and make your
# changes there instead.

services:
  ac-database:
    container_name: ac-database
    image: mysql:8.3
    networks:
      - ac-network
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD_SECRET_FILE: /run/secrets/docker_db_root_password
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql
      - ./apps/docker/read_secrets.sh:/usr/local/bin/read_secrets.sh
    entrypoint: /usr/local/bin/read_secrets.sh mysqld
    restart: unless-stopped
    healthcheck:
      test: "source /usr/local/bin/read_secrets.sh; /usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 40
    secrets:
      - docker_db_root_password

  ac-db-import:
    container_name: ac-db-import
    image: acore/ac-wotlk-db-import:${DOCKER_IMAGE_TAG:-master}
    networks:
      - ac-network
    build:
      context: .
      target: db-import
      dockerfile: apps/docker/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_LOGIN_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_auth
      AC_WORLD_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_world
      AC_CHARACTER_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_characters
    volumes:
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
    depends_on:
      ac-database:
        condition: service_healthy
    secrets:
      - docker_db_dsn_auth
      - docker_db_dsn_world
      - docker_db_dsn_characters

  ac-worldserver:
    container_name: ac-worldserver
    image: acore/ac-wotlk-worldserver:${DOCKER_IMAGE_TAG:-master}
    build:
      context: .
      target: worldserver
      dockerfile: apps/docker/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    networks:
      - ac-network
    ipc: service:ac-authserver
    pid: service:ac-authserver
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
        ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_LOGIN_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_auth
      AC_WORLD_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_world
      AC_CHARACTER_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_characters
      AC_PLAYERBOTS_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_playerbots
    ports:
      - ${DOCKER_WORLD_EXTERNAL_PORT:-8085}:8085
      - ${DOCKER_SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
      # client data
      - ${DOCKER_VOL_DATA:-ac-client-data}:/azerothcore/env/dist/data/:ro
      # module data
      - ${DOCKER_VOL_MOD_PLAYERBOT:-./modules/mod-playerbots}:/azerothcore/modules/mod-playerbots
    depends_on:
      ac-database:
        condition: service_healthy
      ac-db-import:
        condition: service_completed_successfully
      ac-client-data-init:
        condition: service_completed_successfully
    secrets:
      - docker_db_dsn_auth
      - docker_db_dsn_world
      - docker_db_dsn_characters
      - docker_db_dsn_playerbots

  ac-authserver:
    container_name: ac-authserver
    image: acore/ac-wotlk-authserver:${DOCKER_IMAGE_TAG:-master}
    build:
      context: .
      target: authserver
      dockerfile: apps/docker/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    networks:
      - ac-network
    ipc: shareable
    pid: shareable
    tty: true
    restart: unless-stopped
    env_file:
        ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_TEMP_DIR: "/azerothcore/env/dist/temp"
      AC_LOGIN_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_auth
    volumes:
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/azerothcore/env/dist/etc
      # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
      - ${DOCKER_VOL_LOGS:-./env/dist/logs}:/azerothcore/env/dist/logs:delegated
    ports:
      - ${DOCKER_AUTH_EXTERNAL_PORT:-3724}:3724
    depends_on:
      ac-database:
        condition: service_healthy
      ac-db-import:
        condition: service_completed_successfully
    secrets:
      - docker_db_dsn_auth
      - docker_db_dsn_world
      - docker_db_dsn_characters

  ac-client-data-init:
    container_name: ac-client-data-init
    image: acore/ac-wotlk-client-data:${DOCKER_IMAGE_TAG:-master}
    build:
      context: .
      target: client-data
      dockerfile: apps/docker/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    volumes:
      - ${DOCKER_VOL_CLIENT_DATA:-ac-client-data}:/azerothcore/env/dist/data

  # used for extracting maps from files shipped with game client
  # Most of the time this shouldn't be needed
  ac-tools:
    container_name: ac-tools
    image: acore/ac-wotlk-tools:${DOCKER_IMAGE_TAG:-master}
    build:
      context: .
      target: tools
      dockerfile: apps/docker/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    working_dir: /azerothcore/env/client/
    volumes:
      # this is not the directory of the extracted data! It's the client folder used by the extractors
      - ${DOCKER_AC_CLIENT_FOLDER:-./var/client}:/azerothcore/env/dist/bin/Data
    # Activate with `docker compose --profile tools ...`
    profiles: [tools]

  # Dev server with the ./azerothcore folder binded from the host
  # Please use Linux, WSL2 or any ext-compatible filesystem
  # to avoid performance issues
  #
  # This is primarily intended for use with the "devcontainer" project
  #
  # This is provided primarily for development, though it doesn't receive
  # first-class support
  ac-dev-server:
    tty: true
    image: acore/ac-wotlk-dev-server:${DOCKER_IMAGE_TAG:-master}
    build:
      context: .
      dockerfile: ./apps/docker/Dockerfile.dev-server
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
      target: dev
    env_file:
        ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGS_DIR: "/azerothcore/env/dist/logs"
      AC_LOGIN_DATABASE_INFO_SECRET_FILE: /run/secrets/docker_db_dsn_auth
      AC_WORLD_DATABASE_INFO_SECRET_FILE:  /run/secrets/docker_db_dsn_world
      AC_CHARACTER_DATABASE_INFO_SECRET_FILE:  /run/secrets/docker_db_dsn_characters
    secrets:
      - docker_db_dsn_auth
      - docker_db_dsn_world
      - docker_db_dsn_characters
      - docker_db_dsn_playerbots
    ports:
      - ${DOCKER_AUTH_EXTERNAL_PORT:-3724}:3724
      - ${DOCKER_WORLD_EXTERNAL_PORT:-8085}:8085
      - ${DOCKER_SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - ${DOCKER_VOL_ROOT:-.}:/azerothcore:cached
      # [osxfs optimization]: https://stackoverflow.com/a/63437557/1964544
      - ac-build-dev:/azerothcore/var/build
      - ac-ccache-dev:/azerothcore/var/ccache
      # this is not the directory of the extracted data! It's the client folder used by the extractors
      - ${DOCKER_AC_CLIENT_FOLDER:-./var/client}:/azerothcore/env/dist/bin/Data
    # Activate with `docker compose --profile dev ...`
    profiles: [dev]
    depends_on:
      ac-database:
        condition: service_healthy

  ac-wowmgr:
    image: wowmgr:${DOCKER_IMAGE_TAG:-master}
    build:
      context: /usr/local/wowmgr/
      dockerfile: /usr/local/wowmgr/Dockerfile
      args:
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    environment:
      SQLALCHEMY_DSN_SECRET_FILE:  /run/secrets/sqlalchemy_dsn
    secrets:
      - sqlalchemy_dsn
    networks:
      - ac-network
    ports:
      - ${DOCKER_MANAGER_PORT:-3000}:3000
    volumes:
      - ${DOCKER_BIG_STATIC_DIR:-/usr/local/static/}:/wowmgr/static/big/
    depends_on:
      ac-database:
        condition: service_healthy
  ac-caddy:
    image: caddy:2.8.4-alpine
    volumes:
      - /etc/caddy:/caddy
      - /etc/caddy/data:/data
    networks:
      - ac-network
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    command: caddy run -c /caddy/Caddyfile

secrets:
  docker_db_root_password:
    file: /etc/azerothcore/secrets/db_pass
  docker_db_dsn_auth:
    file: /etc/azerothcore/secrets/db_dsn_auth
  docker_db_dsn_world:
    file: /etc/azerothcore/secrets/db_dsn_world
  docker_db_dsn_characters:
    file: /etc/azerothcore/secrets/db_dsn_characters
  docker_db_dsn_playerbots:
    file: /etc/azerothcore/secrets/db_dsn_playerbots
  sqlalchemy_dsn:
    file: /etc/azerothcore/secrets/sqlalchemy_dsn

volumes:
  ac-database:
  ac-client-data:
  # Used for dev server
  ac-build-dev:
  ac-ccache-dev:

networks:
  ac-network:
